server.port=8080

# 1. 換咗做 Pooler Host，同埋 Port 必須係 6543
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres

# 2. Username 必須係 postgres.[你個專案ID] 嘅格式
spring.datasource.username=postgres.zlsjfoxxhdjkrntsmhou

# 3. 填返你真實嘅資料庫密碼
spring.datasource.password=aA39919962..

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect